//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarsadWebsiteControlPanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agency
    {
        public string AgencyID { get; set; }
        public string AgencyArabicName { get; set; }
        public string AgencyEnglishName { get; set; }
        public string AgencyEnglishNameAbbreviation { get; set; }
        public Nullable<int> AgencyCategoryID { get; set; }
    }
}
