//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarsadWebsiteControlPanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Current_Consumer_Old12082017
    {
        public string ConsumerID { get; set; }
        public string ConsumerName { get; set; }
        public string ConsumerCurrentlyOnGSB { get; set; }
        public string ConsumerToBeOnGSB { get; set; }
    }
}
