//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarsadWebsiteControlPanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Current_Agency
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Current_Agency()
        {
            this.tb_Current_Activation = new HashSet<tb_Current_Activation>();
            this.tb_Current_Activation1 = new HashSet<tb_Current_Activation>();
            this.tb_Current_GSBService = new HashSet<tb_Current_GSBService>();
            this.tb_List_AgencyCategory = new HashSet<tb_List_AgencyCategory>();
        }
    
        public string AgencyID { get; set; }
        public string AgencyArabicName { get; set; }
        public string AgencyEnglishName { get; set; }
        public string AgencyEnglishNameAbbreviation { get; set; }
        public Nullable<int> AgencyCategoryID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Current_Activation> tb_Current_Activation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Current_Activation> tb_Current_Activation1 { get; set; }
        public virtual tb_Current_Consumer tb_Current_Consumer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Current_GSBService> tb_Current_GSBService { get; set; }
        public virtual tb_Current_Provider tb_Current_Provider { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_List_AgencyCategory> tb_List_AgencyCategory { get; set; }
    }
}
