//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarsadWebsiteControlPanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Current_MarsadDataset
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Current_MarsadDataset()
        {
            this.tb_Current_Intersection_MarsadDataset_GSBService = new HashSet<tb_Current_Intersection_MarsadDataset_GSBService>();
            this.tb_Current_Intersection_Service_Dataset = new HashSet<tb_Current_Intersection_Service_Dataset>();
        }
    
        public int DatasetID { get; set; }
        public string DatasetFullName { get; set; }
        public string DatasetShortName { get; set; }
        public string GSBServiceCode { get; set; }
        public string GSBDatasetFullName { get; set; }
        public string GSBDatasetShortName { get; set; }
        public string DatasetAvaiableOnGSB { get; set; }
        public string ProviderID { get; set; }
        public string GSBProviderID { get; set; }
        public Nullable<bool> ShowInResult { get; set; }
        public string Comments { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Current_Intersection_MarsadDataset_GSBService> tb_Current_Intersection_MarsadDataset_GSBService { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Current_Intersection_Service_Dataset> tb_Current_Intersection_Service_Dataset { get; set; }
    }
}
