//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarsadWebsiteControlPanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Current_Intersection_MarsadDataset_GSBService
    {
        public int DatasetID { get; set; }
        public string DatasetFullName { get; set; }
        public string GSBServiceCode { get; set; }
        public string GSBDatasetShortName { get; set; }
        public string DatasetAvaiableOnGSB { get; set; }
        public string ProviderID { get; set; }
        public string GSBProviderID { get; set; }
        public Nullable<bool> ShowInResult { get; set; }
        public string Comments { get; set; }
    
        public virtual tb_Current_GSBService tb_Current_GSBService { get; set; }
        public virtual tb_Current_MarsadDataset tb_Current_MarsadDataset { get; set; }
    }
}
