//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarsadWebsiteControlPanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Current_Activation_Old
    {
        public string AgencyID { get; set; }
        public Nullable<int> DatasetID { get; set; }
        public string DatasetActivated { get; set; }
        public int GSBDatasetID { get; set; }
        public Nullable<System.DateTime> ImportingDate { get; set; }
        public string VersionNumber { get; set; }
        public string VersionDate { get; set; }
        public string DataSourceName { get; set; }
    }
}
