//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarsadWebsiteControlPanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Current_GSBOperation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Current_GSBOperation()
        {
            this.tb_Current_Activation = new HashSet<tb_Current_Activation>();
        }
    
        public string OperationCode { get; set; }
        public string OperationArabicName { get; set; }
        public string OperationEnglishName { get; set; }
        public string ServiceCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Current_Activation> tb_Current_Activation { get; set; }
        public virtual tb_Current_GSBService tb_Current_GSBService { get; set; }
    }
}
