//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarsadWebsiteControlPanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Current_Service_AllData11102016
    {
        public string AgencyName { get; set; }
        public string ServiceID { get; set; }
        public string ServiceArabicName { get; set; }
        public string ServiceEnglishName { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<int> ServiceTypeID { get; set; }
        public Nullable<int> ServiceClassificationID { get; set; }
        public Nullable<int> ServiceGeographicalCoverageID { get; set; }
        public Nullable<double> ServiceFees { get; set; }
        public string FinancedByYesser { get; set; }
        public Nullable<double> TimeTakenToDelivereTheServiceNow { get; set; }
        public Nullable<double> TimeTakenToDelivereTheServiceInFuture { get; set; }
        public string OutsideBranchesToProvideTheService { get; set; }
        public string DigitalCertificateIssued { get; set; }
        public Nullable<int> ServiceMaturityLevelID { get; set; }
        public Nullable<int> HigherMaturityServiceLevelToBeReachedID { get; set; }
        public string HigriDateForTransmissitingServiceToTopMaturityLevel { get; set; }
        public string GregorianDateForTransmissitingServiceToTopMaturityLevel { get; set; }
        public Nullable<int> ServiceTargetAudienceNumberID { get; set; }
        public Nullable<int> ServiceNumberOfBeneficiariesInElectronicFormAnnuallyID { get; set; }
        public Nullable<int> ServiceNumberOfElectronicTransactionsPerYearID { get; set; }
        public Nullable<int> ServiceRepeatedNumberOfUsePerBeneficiaryID { get; set; }
        public Nullable<int> ServiceAutomationPortabilityInItsCurrentStateID { get; set; }
        public Nullable<int> ServiceRequirementsAndProceduresForServiceAvailableID { get; set; }
        public Nullable<int> ServiceHasDocumentedProceduresID { get; set; }
        public Nullable<int> ServiceHasWorkflowChartID { get; set; }
        public Nullable<int> ServiceHasProcessReengineeredID { get; set; }
        public Nullable<int> ServiceHasUnifiedProcessesID { get; set; }
        public string ArabicHyperLink { get; set; }
        public string EnglishHyperLink { get; set; }
        public string YouTubeLink { get; set; }
        public string ServiceManual { get; set; }
        public string ServiceForm { get; set; }
        public string ServiceArabicDescription { get; set; }
        public string ServiceEnglishDescription { get; set; }
        public Nullable<int> NumberOfServiceRequestProcessedManuallyIn6Months { get; set; }
        public Nullable<int> NumberOfServiceRequestProcessedElectronically6Months { get; set; }
        public Nullable<int> ServicePriorityID { get; set; }
        public string MyComments { get; set; }
        public Nullable<System.DateTime> ImportingDate { get; set; }
        public string VersionNumber { get; set; }
        public string VersionDate { get; set; }
        public string DataSourceName { get; set; }
    }
}
