//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarsadWebsiteControlPanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Current_Service
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Current_Service()
        {
            this.tb_Current_Intersection_Service_Dataset = new HashSet<tb_Current_Intersection_Service_Dataset>();
            this.tb_Current_Intersection_Service_ServiceChannel = new HashSet<tb_Current_Intersection_Service_ServiceChannel>();
            this.tb_Current_Intersection_Service_ServiceTypeByBeneficary = new HashSet<tb_Current_Intersection_Service_ServiceTypeByBeneficary>();
            this.tb_Current_Service1 = new HashSet<tb_Current_Service>();
            this.tb_Current_Service2 = new HashSet<tb_Current_Service>();
            this.tb_List_StepToApplyForTheService = new HashSet<tb_List_StepToApplyForTheService>();
        }
    
        public string ConsumerID { get; set; }
        public string AgencyName { get; set; }
        public string ServiceID { get; set; }
        public string ServiceArabicName { get; set; }
        public string ServiceEnglishName { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<int> ServiceTypeID { get; set; }
        public Nullable<int> ServiceClassificationID { get; set; }
        public Nullable<int> ServiceGeographicalCoverageID { get; set; }
        public Nullable<int> ServicePriorityID { get; set; }
        public Nullable<double> ServiceFees { get; set; }
        public string FinancedByYesser { get; set; }
        public Nullable<double> TimeTakenToDelivereTheServiceNow { get; set; }
        public Nullable<double> TimeTakenToDelivereTheServiceInFuture { get; set; }
        public string OutsideBranchesToProvideTheService { get; set; }
        public string DigitalCertificateIssued { get; set; }
        public Nullable<int> ServiceMaturityLevelID { get; set; }
        public Nullable<int> HigherMaturityServiceLevelToBeReachedID { get; set; }
        public string HigriDateForTransmissitingServiceToTopMaturityLevel { get; set; }
        public string GregorianDateForTransmissitingServiceToTopMaturityLevel { get; set; }
        public Nullable<int> ServiceTargetAudienceNumberID { get; set; }
        public Nullable<int> ServiceNumberOfBeneficiariesInElectronicFormAnnuallyID { get; set; }
        public Nullable<int> ServiceNumberOfElectronicTransactionsPerYearID { get; set; }
        public Nullable<int> ServiceRepeatedNumberOfUsePerBeneficiaryID { get; set; }
        public Nullable<int> ServiceAutomationPortabilityInItsCurrentStateID { get; set; }
        public Nullable<int> ServiceRequirementsAndProceduresForServiceAvailableID { get; set; }
        public Nullable<int> ServiceHasDocumentedProceduresID { get; set; }
        public Nullable<int> ServiceHasWorkflowChartID { get; set; }
        public Nullable<int> ServiceHasProcessReengineeredID { get; set; }
        public Nullable<int> ServiceHasUnifiedProcessesID { get; set; }
        public string ArabicHyperLink { get; set; }
        public string EnglishHyperLink { get; set; }
        public string YouTubeLink { get; set; }
        public string ServiceManual { get; set; }
        public string ServiceForm { get; set; }
        public string ServiceArabicDescription { get; set; }
        public string ServiceEnglishDescription { get; set; }
        public Nullable<int> NumberOfServiceRequestProcessedManuallyIn6Months { get; set; }
        public Nullable<int> NumberOfServiceRequestProcessedElectronically6Months { get; set; }
        public string MyComments { get; set; }
        public string ImportingDate { get; set; }
        public string VersionNumber { get; set; }
        public string VersionDate { get; set; }
        public string DataSourceName { get; set; }
        public string ActionTaken { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Current_Intersection_Service_Dataset> tb_Current_Intersection_Service_Dataset { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Current_Intersection_Service_ServiceChannel> tb_Current_Intersection_Service_ServiceChannel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Current_Intersection_Service_ServiceTypeByBeneficary> tb_Current_Intersection_Service_ServiceTypeByBeneficary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Current_Service> tb_Current_Service1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Current_Service> tb_Current_Service2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_List_StepToApplyForTheService> tb_List_StepToApplyForTheService { get; set; }
    }
}
