//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarsadWebsiteControlPanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Current_MarsadDataset_Old
    {
        public int DatasetID { get; set; }
        public string DatasetFullName { get; set; }
        public string DatasetShortName { get; set; }
        public Nullable<int> GSBDatasetID { get; set; }
        public string GSBDatasetFullName { get; set; }
        public string GSBDatasetShortName { get; set; }
        public string DatasetAvaiableOnGSB { get; set; }
        public string ProviderID { get; set; }
        public string GSBProviderID { get; set; }
        public Nullable<bool> ShowInResult { get; set; }
        public Nullable<int> GSBServiceID { get; set; }
    }
}
