//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarsadWebsiteControlPanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_List_ServiceChannel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_List_ServiceChannel()
        {
            this.tb_Current_Intersection_Service_ServiceChannel = new HashSet<tb_Current_Intersection_Service_ServiceChannel>();
        }
    
        public int ID { get; set; }
        public int ServiceChannelID { get; set; }
        public string ServiceChannelName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Current_Intersection_Service_ServiceChannel> tb_Current_Intersection_Service_ServiceChannel { get; set; }
    }
}
