//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarsadWebsiteControlPanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_List_ServiceTypeByBeneficiary
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_List_ServiceTypeByBeneficiary()
        {
            this.tb_Current_Intersection_Service_ServiceTypeByBeneficary = new HashSet<tb_Current_Intersection_Service_ServiceTypeByBeneficary>();
        }
    
        public int ID { get; set; }
        public int ServiceTypeByBeneficiaryID { get; set; }
        public string ServiceTypeByBeneficiaryName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Current_Intersection_Service_ServiceTypeByBeneficary> tb_Current_Intersection_Service_ServiceTypeByBeneficary { get; set; }
    }
}
