//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarsadWebsiteControlPanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Test_Services_ImportedByWizard_AsIs_AllData20170119_Main_V1_ServiceCard_CheckingURLs
    {
        public string AgencyID { get; set; }
        public string AgencyName { get; set; }
        public string ServiceID { get; set; }
        public string ServiceArabicName { get; set; }
        public string ArabicHyperLink { get; set; }
        public string OldResult { get; set; }
        public string Oldresult2 { get; set; }
        public string result1 { get; set; }
        public string detalis1 { get; set; }
        public string result { get; set; }
        public string detalis { get; set; }
    }
}
