//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarsadWebsiteControlPanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Test_Services_ImportedByWizard_AsIs_AllData20170119_Main_V1_ISCToBeUpdated
    {
        public string ServiceID { get; set; }
        public int ServiceChannelID { get; set; }
        public string ImportingDate { get; set; }
        public string VersionNumber { get; set; }
        public string VersionDate { get; set; }
        public string DataSourceName { get; set; }
    }
}
