//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarsadWebsiteControlPanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_NumberOfTimesDatasetUsed
    {
        public int DatasetID { get; set; }
        public string DatasetName { get; set; }
        public Nullable<int> TotalNumberDatasetUsed { get; set; }
    }
}
