//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarsadWebsiteControlPanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_Providers2
    {
        public string ProviderID { get; set; }
        public string ProviderName { get; set; }
        public Nullable<int> NumberOfServicesDependOnIt { get; set; }
    }
}
